// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZCklH5V6Ab8wKxfC7wCXblCuyb30qjgk',
    appId: '1:415988989931:web:6c132be33adfd64bf063ae',
    messagingSenderId: '415988989931',
    projectId: 'appdev-practise',
    authDomain: 'appdev-practise.firebaseapp.com',
    storageBucket: 'appdev-practise.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWItSIQu5K8XND5eGzObpTxL5c1NCaR-g',
    appId: '1:415988989931:android:6b814b2b66f5c07df063ae',
    messagingSenderId: '415988989931',
    projectId: 'appdev-practise',
    storageBucket: 'appdev-practise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvEtzW_MPzdANefe87L5hPTgXL6LzV-ME',
    appId: '1:415988989931:ios:46be34eb88ef7f96f063ae',
    messagingSenderId: '415988989931',
    projectId: 'appdev-practise',
    storageBucket: 'appdev-practise.appspot.com',
    iosBundleId: 'com.example.appDevAssignment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvEtzW_MPzdANefe87L5hPTgXL6LzV-ME',
    appId: '1:415988989931:ios:e9ddecb227f908a7f063ae',
    messagingSenderId: '415988989931',
    projectId: 'appdev-practise',
    storageBucket: 'appdev-practise.appspot.com',
    iosBundleId: 'com.example.appDevAssignment2.RunnerTests',
  );
}
